#! /bin/sh

#
# .profile
# Login-Shell specific *terminal-only* common shell configuration

# If in a graphical session, that's not Gnome started by GDM, manually load
# Session Startup files alike to
# https://wiki.gnome.org/Initiatives/Wayland/SessionStart
envdgenerator='/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator'
if [ -n "$WAYLAND_DISPLAY" ] || [ -n "$XDG_SESSION_TYPE" ] || [ -n "$DISPLAY" ]; then
	if [ "$GDMSESSION" != "gnome" ]; then
		if [ -f "$envdgenerator" ]; then
			while read -r line; do
				export "$line";
			done < "$envdgenerator"
		fi
	fi
fi
