#! /bin/sh

#
# .profile
# Login-Shell specific *terminal-only* common shell configuration

# If in a session, that's not Gnome started by GDM, manually load
# Session Startup files alike to
# https://wiki.gnome.org/Initiatives/Wayland/SessionStart
envdgenerator='/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator'
if [ "$GDMSESSION" != "gnome" ]; then
	if [ -f "$envdgenerator" ]; then
		# We cannot pipe the output of the generator into the
		# while since the pipeline *may* be executed in a
		# subshell.
		tmp=$(mktemp)
		touch "$tmp"
		chmod go= "$tmp"
		"$envdgenerator" > "$tmp"
		while read -r line; do
			export "$line";
		done < "$tmp"
		rm -f "$tmp"
	fi
fi
