# Enable plugin plugin :)
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload


hook global BufCreate .*[.](cs) %{
    set-option buffer filetype csharp
}



# Enable LSP support
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    # uncomment to enable debugging
    #eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
    #set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    hook global WinSetOption filetype=(rust|c|cpp|latex|context) %{
        lsp-enable-window
        lsp-auto-hover-enable
    }
}

# Enable editorconfig support
hook global WinCreate ^[^*]+$ %{editorconfig-load}

# Buffer fallbacks
#hook global WinSetOption filetype=(c|cpp) %{
#    set-option buffer indentwidth 8
#    set-option buffer tabstop %opt{indentwidth}
#}
#hook global WinSetOption filetype=(latex|context) %{
#    set-option buffer indentwidth 2
#    set-option buffer tabstop %opt{indentwidth}
#}

# Configure tab behavior
plug "andreyorst/smarttab.kak" defer smarttab %{
    # Backspace: Delete 8 spaces / 1 Tab
    set-option global softtabstop %opt{indentwidth}
    set-option global tabstop %opt{indentwidth}
} config %{
    hook global WinSetOption filetype=(rust|markdown|kak|sh|perl|latex|context) expandtab
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    hook global WinSetOption filetype=(c|cpp) smarttab
    hook global WinSetOption filetype=(latex) smarttab
}

hook global BufSetOption filetype=(latex|context) %{
    declare-option str document
    declare-option str documenttrunk

    declare-option str pdfviewer
    set-option buffer pdfviewer "okular"
    declare-option str pdfvieweropts
    set-option buffer pdfvieweropts "--unique"

    # printf ${kak_opt_pdfviewerfmt} $pdf $line $tex
    declare-option str pdfviewerfmt
    set-option buffer pdfviewerfmt "'%%s#src:%%d %%s'"

    # Search for `!TeX root` magic
    evaluate-commands %sh{
        buffer="$kak_buffile"
        magic=$(grep '^% !TeX root = ' "$buffer" | sed 's/.*= //' -)
        root=${magic:-$buffer}
        trunk=$(echo "$root" | sed 's/\.[^\.]*$//' - )

        echo "set-option buffer document ${root}"
        echo "set-option buffer documenttrunk ${trunk}"
    }

    declare-option str buildcmd
    set-option buffer buildcmd ':make<ret>:evaluate-commands -try-client %opt{jumpclient} %{nop}<ret>'
    map -docstring "build & view" global user , %opt{buildcmd}
    map -docstring "view" global user v ':pdf-view %opt{documenttrunk}<ret>'
}

# LaTeXmk suppport
hook global BufSetOption filetype=(latex) %{
    set-option buffer makecmd "latexmk -pvc -view=none %opt{document}"
}

hook global BufSetOption filetype=(context) %{
    set-option buffer makecmd "context --paranoid --errors=list --nonstopmode %opt{document}"
}

# Use bear make wrapper.
hook global BufSetOption filetype=(c|cpp) %{
    set-option buffer makecmd "bear make"
}


define-command -params 1 pdf-view %{
    nop %sh{
        pdf="${1}.pdf"
        tex="${1}.tex"
        line=${kak_cursor_line}
        args=$(printf "${kak_opt_pdfviewerfmt}" $pdf $line $tex)
        ${kak_opt_pdfviewer} ${kak_opt_pdfvieweropts} "$pdf#src:$line $tex" >/tmp/bar 2>&1 </dev/null &
        echo ${kak_opt_pdfviewer} ${kak_opt_pdfvieweropts} ${args} >/tmp/foo
    }
}

# From wiki
def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

#    new rename-client docs
#    set global docsclient docs
}

# Highlight column
add-highlighter global/ column '%opt{autowrap_column}' default,red

#require-module x11
#set-option global termcmd 'konsole -e'
#set-option terminal 'kitty'

try %{ source ./.kakrc }
