# Editor
export VISUAL=kak
export EDITOR=kak

# XDG Base Directories
## Defaults
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

## Flatpak
export XDG_DATA_DIRS=$XDG_DATA_DIRS:/var/lib/flatpak/exports/share
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$XDG_DATA_HOME/flatpak/exports/share

## Adhere to XDG
export LEDGER_FILE=$XDG_DATA_HOME/hledger/hledger.journal
export TEXMFHOME=$XDG_DATA_HOME/texmf
export LESSHISTFILE=$XDG_CACHE_HOME/less/history 
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export npm_config_prefix=$XDG_DATA_HOME/node_modules
export CARGO_HOME=$XDG_DATA_HOME/cargo
export RUSTUP_HOME=$XDG_DATA_HOME/rustup

# PATH
export PATH=$npm_config_prefix/bin:$PATH
export PATH=$CARGO_HOME/bin:$PATH
if command -v luarocks >/dev/null; then
  eval `luarocks path --append`
fi
export PATH=$HOME/.local/bin:$PATH
