#! /usr/bin/bash

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000000
HISTFILESIZE=1000000
shopt -s histappend

source ~/.aliases
