#! /usr/bin/bash

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000000
HISTFILESIZE=1000000
shopt -s histappend

alias ls='ls --color=auto'
shtart() {
    nohup "$@" >/dev/null 2>&1 &!
}
open() {
    shtart xdg-open "$@"
}

alias makeup='podman run --net none --rm=true -v /:/host registry:5000/greg/markup_tool:latest make -f /usr/local/markup_template/auxiliary/Makefile -C  /host/$(pwd)'
alias pandoc='podman run --rm -v "$(pwd):/data" docker.io/pandoc/latex:latest '

infohtml() {
    for page; do
        open "https://www.gnu.org/software/$page/manual/$page.html"
    done
}

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

# Git aliases
alias g='git'
alias gb='git branch'
alias ga='git add'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias gc='git commit'
alias gco='git checkout'
alias gcmsg='git commit -m'

alias make='bear -- make'

alias bc='bc -q'

# Safeguard to force sudoedit
_sudo=$(command -v sudo)
function sudo {
    case $1 in
    $VISUAL|$EDITOR)
        shift
        sudoedit ${@}
        ;;
    *)
        $_sudo $@
        ;;
    esac
}

# Most remotes do not speak cat.
#if [ "$TERM" = "xterm-kitty" ]; then
#    alias ssh='env TERM=xterm-256color ssh'
#fi
